package com.bendmasterpro.app;

import android.graphics.Color;
import android.graphics.Canvas;
import android.graphics.Paint;
import android.graphics.Path;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.os.Bundle;
import android.content.SharedPreferences;
import org.json.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.*;
import java.util.*;

public class MainActivity extends AppCompatActivity {
 final int BG=Color.rgb(15,27,47), CARD=Color.rgb(30,43,63), INPUT=Color.rgb(53,70,91), BORDER=Color.rgb(48,65,86), TXT=Color.rgb(239,243,248), MUT=Color.rgb(148,163,184), BLUE=Color.rgb(96,165,250);
 LinearLayout page,resultBox,customDieWrap,flangeBox,flatResultBox; Spinner mat,dieSpin; EditText thick,punch,angle,length,f1,f2,bends,customDie; TextView punchConv,lenConv; boolean metric=false; ArrayList<EditText> flangeFields=new ArrayList<>(); ArrayList<Boolean> flangeUp=new ArrayList<>(); FlatDiagram flatDiagram; FormedDiagram formedDiagram;
 int sharedMat=2; String sharedT="",sharedD="",sharedR="0.030",sharedA="90",sharedL="1";
 final String[] names={"5052-H32 Aluminum","6061-T6 Aluminum","A572 Gr42","A572 Gr50","CRS","HRPO A36","304 Stainless","316 Stainless"};
 final String[] cats={"aluminum","aluminum","steel","steel","steel","steel","stainless","stainless"};
 final double[] k={.41,.41,.44,.44,.44,.44,.43,.43}, tensile={33000,45000,60000,65000,55000,58000,75000,85000};
 boolean materialManageMode=false;ArrayList<String> materialNames=new ArrayList<>(),materialCats=new ArrayList<>();ArrayList<Double> materialK=new ArrayList<>(),materialTensile=new ArrayList<>();String[] dies;
 int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
 GradientDrawable box(int c,int stroke,int rad){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(dp(rad));g.setStroke(dp(1),stroke);return g;}
 TextView t(String s,float z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);return v;}
 void mg(View v,int l,int top,int r,int b){ViewGroup.MarginLayoutParams p=(ViewGroup.MarginLayoutParams)v.getLayoutParams();p.setMargins(dp(l),dp(top),dp(r),dp(b));v.setLayoutParams(p);}
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.BLACK);getWindow().setNavigationBarColor(BG);loadMaterials();dies=dieOptions();showCalc();}
 String[] currentNames(){return materialNames.toArray(new String[0]);}
 void loadMaterials(){materialNames.clear();materialCats.clear();materialK.clear();materialTensile.clear();String data=getSharedPreferences("materials",MODE_PRIVATE).getString("data",null);if(data!=null){try{JSONArray a=new JSONArray(data);for(int i=0;i<a.length();i++){JSONObject o=a.getJSONObject(i);materialNames.add(o.getString("name"));materialCats.add(o.getString("category"));materialK.add(o.getDouble("k"));materialTensile.add(o.getDouble("tensile"));}return;}catch(Exception ignored){}}for(int i=0;i<names.length;i++){materialNames.add(names[i]);materialCats.add(cats[i]);materialK.add(k[i]);materialTensile.add(tensile[i]);}}
 void persistMaterials(){JSONArray a=new JSONArray();try{for(int i=0;i<materialNames.size();i++){JSONObject o=new JSONObject();o.put("name",materialNames.get(i));o.put("category",materialCats.get(i));o.put("k",materialK.get(i));o.put("tensile",materialTensile.get(i));a.put(o);}}catch(Exception ignored){}getSharedPreferences("materials",MODE_PRIVATE).edit().putString("data",a.toString()).apply();}
 String[] dieOptions(){ArrayList<String> a=new ArrayList<>();a.add("Select die width");for(int mm=5;mm<=30;mm++){if(metric)a.add(mm+" mm ("+String.format(Locale.US,"%.3f",mm/25.4)+" in)");else a.add(String.format(Locale.US,"%.3f in (%d mm)",mm/25.4,mm));}a.add("Custom...");return a.toArray(new String[0]);}
 double selectedDie(){if(dieSpin==null)return Double.NaN;int p=dieSpin.getSelectedItemPosition();if(p<=0)return Double.NaN;if(p==dies.length-1){double x=val(customDie);return metric?x/25.4:x;}int mm=p+4;return mm/25.4;}
 void setupDie(LinearLayout parent){dies=dieOptions();dieSpin=spinner(parent,metric?"Die Width (mm)":"Die Width (in)",dies);customDieWrap=new LinearLayout(this);customDieWrap.setOrientation(LinearLayout.VERTICAL);parent.addView(customDieWrap);customDie=field(customDieWrap,metric?"Custom Die Width (mm)":"Custom Die Width (in)","");customDieWrap.setVisibility(View.GONE);dieSpin.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int pos,long id){customDieWrap.setVisibility(pos==dies.length-1?View.VISIBLE:View.GONE);}});if(!sharedD.isEmpty()){try{double in=Double.parseDouble(sharedD),mm=in*25.4;int whole=(int)Math.round(mm);if(whole>=5&&whole<=30&&Math.abs(mm-whole)<.02)dieSpin.setSelection(whole-4);else{dieSpin.setSelection(dies.length-1);customDie.setText(metric?String.format(Locale.US,"%.3f",mm):sharedD);}}catch(Exception e){}}}
 void shell(int active){
  LinearLayout outer=new LinearLayout(this);outer.setOrientation(LinearLayout.VERTICAL);outer.setBackgroundColor(BG);
  ViewCompat.setOnApplyWindowInsetsListener(outer,(v,i)->{Insets x=i.getInsets(WindowInsetsCompat.Type.systemBars());v.setPadding(0,x.top,0,x.bottom);return i;});
  ScrollView sv=new ScrollView(this);page=new LinearLayout(this);page.setOrientation(LinearLayout.VERTICAL);page.setPadding(dp(17),dp(30),dp(17),dp(30));sv.addView(page);outer.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout nav=new LinearLayout(this);nav.setBackgroundColor(Color.rgb(12,22,38));nav.setPadding(0,0,0,dp(4));String[] n={"Calculator","Flat","Materials","FAQ"};
  for(int i=0;i<4;i++){final int q=i;Button b=new Button(this);b.setText(n[i]);b.setTextSize(10);b.setAllCaps(false);b.setTextColor(i==active?BLUE:MUT);b.setBackgroundColor(Color.TRANSPARENT);nav.addView(b,new LinearLayout.LayoutParams(0,dp(52),1));b.setOnClickListener(v->{save();if(q==0)showCalc();else if(q==1)showFlat();else if(q==2)showMaterials();else showFaq();});}outer.addView(nav,new LinearLayout.LayoutParams(-1,dp(56)));setContentView(outer);ViewCompat.requestApplyInsets(outer);
 }
 LinearLayout card(String head){
  LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setBackground(box(CARD,BORDER,12));page.addView(c,new LinearLayout.LayoutParams(-1,-2));mg(c,0,0,0,27);
  TextView h=t(head,18,TXT);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setPadding(dp(27),dp(15),dp(27),dp(15));c.addView(h);
  View line=new View(this);line.setBackgroundColor(BORDER);c.addView(line,new LinearLayout.LayoutParams(-1,dp(1)));
  LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(27),dp(14),dp(27),dp(20));c.addView(body);return body;
 }
 TextView label(LinearLayout c,String s){TextView l=t(s,15,TXT);l.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(l);mg(l,0,10,0,9);return l;}
 EditText field(LinearLayout c,String lab,String val){label(c,lab);EditText e=new EditText(this);e.setText(val);if(lab.startsWith("Material Thickness"))e.setHint(metric?"3.175":"0.125");e.setTextColor(TXT);e.setHintTextColor(Color.rgb(113,128,146));e.setTextSize(17);e.setSingleLine();e.setPadding(dp(14),0,dp(14),0);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setBackground(box(INPUT,Color.rgb(67,86,108),7));c.addView(e,new LinearLayout.LayoutParams(-1,dp(42)));mg(e,0,0,0,10);return e;}
 Spinner spinner(LinearLayout c,String lab,String[] arr){label(c,lab);Spinner s=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,arr){@Override public View getView(int p,View v,ViewGroup g){TextView z=(TextView)super.getView(p,v,g);z.setTextColor(TXT);z.setTextSize(16);z.setPadding(dp(14),0,dp(14),0);return z;}};s.setAdapter(a);s.setBackground(box(INPUT,Color.rgb(67,86,108),7));c.addView(s,new LinearLayout.LayoutParams(-1,dp(42)));mg(s,0,0,0,8);return s;}
 void helper(LinearLayout c,String s){TextView v=t(s,13,BLUE);c.addView(v);mg(v,0,0,0,16);}
 double val(EditText e){try{return Double.parseDouble(e.getText().toString());}catch(Exception x){return Double.NaN;}}
 void save(){if(mat!=null)sharedMat=mat.getSelectedItemPosition();if(thick!=null)sharedT=thick.getText().toString();if(dieSpin!=null&&dieSpin.getSelectedItemPosition()>0){double sd=selectedDie();if(sd>0)sharedD=String.format(Locale.US,"%.6f",sd);}if(punch!=null)sharedR=punch.getText().toString();if(angle!=null)sharedA=angle.getText().toString();if(length!=null)sharedL=length.getText().toString();}
 void watch(EditText e,TextView v){e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){try{v.setText(String.format(Locale.US,"≈ %.3f mm",Double.parseDouble(s.toString())*25.4));}catch(Exception x){v.setText("");}}public void afterTextChanged(Editable e){}});}
 void showCalc(){
  shell(0);LinearLayout in=card("Input Parameters");mat=spinner(in,"Material Type",currentNames());mat.setSelection(sharedMat);
  thick=field(in,"Material Thickness (in)",sharedT);setupDie(in);
  LinearLayout pr=new LinearLayout(this);pr.setOrientation(LinearLayout.HORIZONTAL);pr.setGravity(Gravity.CENTER_VERTICAL);TextView pl=label(pr,"Punch Radius (in)");pr.removeView(pl);pr.addView(pl,new LinearLayout.LayoutParams(-2,-2));punchConv=t("",13,BLUE);pr.addView(punchConv,new LinearLayout.LayoutParams(-2,-2));mg(punchConv,8,10,0,9);in.addView(pr);punch=fieldNoLabel(in,sharedR);
  angle=field(in,"Bend Angle (degrees)",sharedA);LinearLayout lr=new LinearLayout(this);lr.setOrientation(LinearLayout.HORIZONTAL);lr.setGravity(Gravity.CENTER_VERTICAL);TextView ll=label(lr,"Bend Length (in)");lr.removeView(ll);lr.addView(ll,new LinearLayout.LayoutParams(-2,-2));lenConv=t("",13,BLUE);lr.addView(lenConv,new LinearLayout.LayoutParams(-2,-2));mg(lenConv,8,10,0,9);in.addView(lr);length=fieldNoLabel(in,sharedL);watch(punch,punchConv);watch(length,lenConv);punch.setText(sharedR);length.setText(sharedL);
  LinearLayout res=card("Calculation Result");resultBox=res;emptyResult();setupAutoCalc();
  LinearLayout q=card("Quick Reference");ref(q,"Die Size Rule","Steel/Stainless: 4-6× thickness | Aluminum: 6-8× thickness");ref(q,"Common K-Factors","Soft materials: 0.38-0.41 | Hard materials: 0.43-0.46");ref(q,"Typical Punch Radius","Usually 0.031\" - 0.125\" depending on material and tooling");
 }
 EditText fieldNoLabel(LinearLayout c,String val){EditText e=new EditText(this);e.setText(val);e.setTextColor(TXT);e.setTextSize(17);e.setSingleLine();e.setPadding(dp(14),0,dp(14),0);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);e.setBackground(box(INPUT,Color.rgb(67,86,108),7));c.addView(e,new LinearLayout.LayoutParams(-1,dp(42)));mg(e,0,0,0,10);return e;}
 void ref(LinearLayout c,String h,String b){TextView x=t(h,13,TXT);x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);c.addView(x);mg(x,0,8,0,7);TextView y=t(b,13,MUT);c.addView(y);mg(y,0,0,0,7);}
 void emptyResult(){resultBox.removeAllViews();Space s=new Space(this);resultBox.addView(s,new LinearLayout.LayoutParams(1,dp(45)));TextView icon=t("▣",36,MUT);icon.setGravity(Gravity.CENTER);resultBox.addView(icon);TextView h=t("Enter all parameters",17,TXT);h.setTypeface(Typeface.DEFAULT,Typeface.BOLD);h.setGravity(Gravity.CENTER);resultBox.addView(h);mg(h,0,18,0,5);TextView b=t("to calculate bend deduction",14,MUT);b.setGravity(Gravity.CENTER);resultBox.addView(b);Space z=new Space(this);resultBox.addView(z,new LinearLayout.LayoutParams(1,dp(45)));}
 void setupAutoCalc(){TextWatcher w=new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){}public void afterTextChanged(Editable e){autoCalc();}};for(EditText e:new EditText[]{thick,punch,angle,length,customDie})if(e!=null)e.addTextChangedListener(w);mat.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int pos,long id){sharedMat=pos;autoCalc();}});AdapterView.OnItemSelectedListener old=null;dieSpin.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){public void onNothingSelected(AdapterView<?> p){}public void onItemSelected(AdapterView<?> p,View v,int pos,long id){if(customDieWrap!=null)customDieWrap.setVisibility(pos==dies.length-1?View.VISIBLE:View.GONE);autoCalc();}});autoCalc();}
 void autoCalc(){double th=val(thick),r=val(punch),a=val(angle),bl=val(length),d=selectedDie();if(th>0&&r>=0&&a>0&&a<180&&bl>0&&d>0)calc();else if(resultBox!=null)emptyResult();}
 void calc(){save();resultBox.removeAllViews();double th=val(thick),r=val(punch),a=val(angle),bl=val(length);double d=selectedDie();if(!(th>0&&r>=0&&a>0&&a<180&&bl>0&&d>0)){TextView e=t("Enter all parameters to calculate bend deduction.",15,MUT);e.setGravity(Gravity.CENTER);resultBox.addView(e);return;}int i=sharedMat;double er=Math.max(r,d/6),rr=Math.toRadians(a),ba=rr*(er+materialK.get(i)*th),bd=2*Math.tan(rr/2)*(er+th)-ba,tonsFt=1.33*materialTensile.get(i)*th*th/d/2000,total=tonsFt*(bl/12),fl=d/2+bd/2;TextView o=t(String.format(Locale.US,"Bend Deduction\n%.4f in\n\nBend Allowance\n%.4f in\n\nEffective Inside Radius\n%.4f in\n\nRequired Tonnage\n%.2f tons\n\nRecommended Tonnage (+15%%)\n%.0f tons\n\nMinimum Flange\n%.4f in",bd,ba,er,total,Math.ceil(total*1.15),fl),16,TXT);o.setLineSpacing(0,1.15f);resultBox.addView(o);}
 void showFlat(){
  shell(1);flangeFields.clear();flangeUp.clear();
  TextView title=t("Flat Pattern Calculator",28,TXT);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);page.addView(title);mg(title,8,0,0,2);
  TextView sub=t("Calculate total flat length",15,MUT);page.addView(sub);mg(sub,8,0,0,18);
  LinearLayout r=card("Reference Data");mat=spinner(r,"Material Type",currentNames());mat.setSelection(sharedMat);thick=field(r,"Material Thickness (in)",sharedT);setupDie(r);punch=field(r,"Punch Radius (in)",sharedR);angle=field(r,"Bend Angle (degrees)",sharedA);TextView note=t("Reference data is shared with the Bend Deduction Calculator.",13,BLUE);r.addView(note);
  LinearLayout fl=card("Flanges");flangeBox=new LinearLayout(this);flangeBox.setOrientation(LinearLayout.VERTICAL);fl.addView(flangeBox);addFlange();addFlange();Button add=new Button(this);add.setText("+  Add Flange");add.setTextSize(16);add.setAllCaps(false);add.setTextColor(Color.BLACK);add.setBackground(box(Color.WHITE,Color.WHITE,8));fl.addView(add,new LinearLayout.LayoutParams(-1,dp(48)));mg(add,0,10,0,0);add.setOnClickListener(v->{addFlange();updateFlat();});
  flatResultBox=card("Calculation Result");
  LinearLayout formed=card("Formed Part (Side View)");formedDiagram=new FormedDiagram();formed.addView(formedDiagram,new LinearLayout.LayoutParams(-1,dp(220)));
  LinearLayout layout=card("Flat Pattern Layout");flatDiagram=new FlatDiagram();layout.addView(flatDiagram,new LinearLayout.LayoutParams(-1,dp(240)));
  updateFlat();
 }
 void addFlange(){
  final int idx=flangeFields.size();LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);flangeBox.addView(row);
  LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView lab=t("Flange "+(idx+1)+" (in)",15,TXT);lab.setTypeface(Typeface.DEFAULT,Typeface.BOLD);head.addView(lab,new LinearLayout.LayoutParams(0,-2,1));
  Button dir=new Button(this);dir.setText("↑");dir.setTextSize(18);dir.setTextColor(Color.WHITE);dir.setBackground(box(Color.rgb(37,99,235),Color.rgb(37,99,235),7));head.addView(dir,new LinearLayout.LayoutParams(dp(44),dp(40)));row.addView(head);mg(head,0,8,0,6);
  EditText e=fieldNoLabel(row,"");e.setHint("2.000");e.setHintTextColor(Color.rgb(113,128,146));flangeFields.add(e);flangeUp.add(true);
  dir.setOnClickListener(v->{boolean up=!flangeUp.get(idx);flangeUp.set(idx,up);dir.setText(up?"↑":"↓");dir.setBackground(box(up?Color.rgb(37,99,235):Color.rgb(217,119,6),up?Color.rgb(37,99,235):Color.rgb(217,119,6),7));updateFlat();});
  e.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){}public void afterTextChanged(Editable x){updateFlat();}});
 }
 double flatBD(){try{double th=Double.parseDouble(sharedT),r=Double.parseDouble(sharedR),a=Double.parseDouble(sharedA),d=Double.parseDouble(sharedD);double er=Math.max(r,d/6),rr=Math.toRadians(a);return 2*Math.tan(rr/2)*(er+th)-rr*(er+materialK.get(sharedMat)*th);}catch(Exception e){return Double.NaN;}}
 void updateFlat(){
  if(flatResultBox==null)return;save();double sum=0;boolean ok=flangeFields.size()>=2;for(EditText e:flangeFields){double x=val(e);if(!(x>0))ok=false;else sum+=x;}double bd=flatBD();if(!(bd>=0))ok=false;int nb=Math.max(0,flangeFields.size()-1);flatResultBox.removeAllViews();
  if(!ok){TextView x=t("Enter all flange lengths and complete the Reference Data to calculate the flat pattern.",14,MUT);x.setGravity(Gravity.CENTER);flatResultBox.addView(x);mg(x,0,25,0,25);}
  else{double total=sum-nb*bd;TextView h=t("Total Flat Length",15,TXT);h.setGravity(Gravity.CENTER);flatResultBox.addView(h);TextView big=t(String.format(Locale.US,"%.4f in",total),34,Color.WHITE);big.setTypeface(Typeface.DEFAULT,Typeface.BOLD);big.setGravity(Gravity.CENTER);big.setBackground(box(Color.rgb(22,163,74),Color.rgb(22,163,74),12));flatResultBox.addView(big,new LinearLayout.LayoutParams(-1,dp(105)));mg(big,0,8,0,18);TextView br=t(String.format(Locale.US,"Flange total: %.4f in\nBends: %d\nBend deduction: %.4f in each\nTotal bend deduction: %.4f in\n\n%.4f − (%d × %.4f) = %.4f in",sum,nb,bd,nb*bd,sum,nb,bd,total),15,TXT);br.setLineSpacing(dp(3),1f);flatResultBox.addView(br);}
  if(formedDiagram!=null)formedDiagram.invalidate();if(flatDiagram!=null)flatDiagram.invalidate();
 }
 class FormedDiagram extends View{
  Paint p=new Paint(1);FormedDiagram(){super(MainActivity.this);setBackgroundColor(Color.rgb(12,23,43));}
  protected void onDraw(Canvas c){super.onDraw(c);if(flangeFields.size()<2)return;ArrayList<Double> ls=new ArrayList<>();for(EditText e:flangeFields){double z=val(e);if(!(z>0))return;ls.add(z);}double a;try{a=Double.parseDouble(sharedA);}catch(Exception e){a=90;}ArrayList<double[]> pts=new ArrayList<>();double x=0,y=0,heading=0,minX=0,maxX=0,minY=0,maxY=0;pts.add(new double[]{x,y});for(int i=0;i<ls.size();i++){if(i>0)heading+=flangeUp.get(i)?-a:a;x+=Math.cos(Math.toRadians(heading))*ls.get(i);y+=Math.sin(Math.toRadians(heading))*ls.get(i);pts.add(new double[]{x,y});minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);}float pad=dp(34);double rw=Math.max(maxX-minX,.1),rh=Math.max(maxY-minY,.1);float scale=(float)Math.min((getWidth()-2*pad)/rw,(getHeight()-2*pad)/rh);float ox=pad+(float)(-minX*scale)+(getWidth()-2*pad-(float)(rw*scale))/2,oy=pad+(float)(-minY*scale)+(getHeight()-2*pad-(float)(rh*scale))/2;p.setStrokeWidth(dp(3));p.setStyle(Paint.Style.STROKE);p.setColor(Color.rgb(96,165,250));Path path=new Path();path.moveTo(ox+(float)(pts.get(0)[0]*scale),oy+(float)(pts.get(0)[1]*scale));for(int i=1;i<pts.size();i++)path.lineTo(ox+(float)(pts.get(i)[0]*scale),oy+(float)(pts.get(i)[1]*scale));c.drawPath(path,p);p.setStyle(Paint.Style.FILL);p.setTextSize(dp(10));p.setColor(TXT);for(int i=0;i<ls.size();i++){float x1=ox+(float)(pts.get(i)[0]*scale),y1=oy+(float)(pts.get(i)[1]*scale),x2=ox+(float)(pts.get(i+1)[0]*scale),y2=oy+(float)(pts.get(i+1)[1]*scale);String segText=String.format(Locale.US,"F%d %.2f",i+1,ls.get(i));float stw=p.measureText(segText);float mx=(x1+x2)/2,my=(y1+y2)/2;c.drawText(segText,mx-stw/2,my-dp(8),p);}}
 }
 class FlatDiagram extends View{
  Paint p=new Paint(1);FlatDiagram(){super(MainActivity.this);setBackgroundColor(Color.rgb(12,23,43));}
  protected void onDraw(Canvas c){super.onDraw(c);if(flangeFields.size()<2)return;double sum=0;ArrayList<Double> ls=new ArrayList<>();for(EditText e:flangeFields){double x=val(e);if(!(x>0))return;ls.add(x);sum+=x;}double bd=flatBD();if(!(bd>=0))return;double total=sum-(ls.size()-1)*bd;float left=dp(24),right=getWidth()-dp(24),w=right-left,y=getHeight()*.47f,x=left;p.setStyle(Paint.Style.FILL);p.setTextSize(dp(11));for(int i=0;i<ls.size();i++){double developed=ls.get(i)-((i==0||i==ls.size()-1)?bd/2:bd);float seg=(float)(developed/total*w);p.setColor(Color.rgb(70,88,109));c.drawRect(x,y,x+seg,y+dp(30),p);p.setColor(TXT);c.drawText("F"+(i+1),x+seg/2-dp(7),y+dp(20),p);x+=seg;if(i<ls.size()-1){p.setColor(Color.rgb(239,68,68));p.setStrokeWidth(dp(2));c.drawLine(x,y-dp(12),x,y+dp(42),p);p.setColor(flangeUp.get(i+1)?Color.rgb(34,197,94):Color.rgb(245,158,11));c.drawText(flangeUp.get(i+1)?"▲":"▼",x-dp(6),y-dp(16),p);}}p.setColor(TXT);p.setTextSize(dp(12));String totalText=String.format(Locale.US,"Total flat: %.4f in",total);float tw=p.measureText(totalText);c.drawText(totalText,left+(w-tw)/2,y+dp(82),p);
   double cumulative=0;float bx=left;p.setStrokeWidth(dp(1));for(int i=0;i<ls.size()-1;i++){double developed=ls.get(i)-bd/2-(i==0?0:bd/2);cumulative+=developed;bx=left+(float)(cumulative/total*w);p.setColor(MUT);c.drawLine(left,y-dp(34)-i*dp(18),bx,y-dp(34)-i*dp(18),p);c.drawLine(left,y-dp(39)-i*dp(18),left,y-dp(29)-i*dp(18),p);c.drawLine(bx,y-dp(39)-i*dp(18),bx,y-dp(29)-i*dp(18),p);p.setColor(TXT);p.setTextSize(dp(9));c.drawText(String.format(Locale.US,"%.4f in",cumulative),left+(bx-left)/2-dp(18),y-dp(39)-i*dp(18),p);}}
 }
 void showMaterials(){shell(2);TextView title=t("Materials",25,TXT);title.setTypeface(Typeface.DEFAULT,Typeface.BOLD);page.addView(title);
 Button manage=new Button(this);manage.setText(materialManageMode?"Done":"Add / Remove");manage.setAllCaps(false);page.addView(manage,new LinearLayout.LayoutParams(-1,dp(45)));manage.setOnClickListener(v->{materialManageMode=!materialManageMode;showMaterials();});
 ArrayList<CheckBox> checks=new ArrayList<>();
 for(int i=0;i<materialNames.size();i++){final int idx=i;LinearLayout body=card(materialNames.get(i));LinearLayout line=new LinearLayout(this);line.setGravity(Gravity.CENTER_VERTICAL);body.addView(line);
 TextView details=t(String.format(Locale.US,"%s  •  K-factor %.3f  •  Tensile %,.0f PSI",materialCats.get(i).toUpperCase(Locale.US),materialK.get(i),materialTensile.get(i)),13,MUT);line.addView(details,new LinearLayout.LayoutParams(0,-2,1));
 if(materialManageMode){CheckBox check=new CheckBox(this);check.setTag(idx);line.addView(check);checks.add(check);}
 else{TextView edit=t("Edit",15,BLUE);edit.setPadding(dp(12),dp(8),dp(2),dp(8));line.addView(edit);edit.setOnClickListener(v->materialDialog(idx));}}
 if(materialManageMode){Button add=new Button(this);add.setText("+ Add Material");add.setAllCaps(false);add.setTextColor(Color.WHITE);add.setBackground(box(Color.rgb(22,163,74),Color.rgb(22,163,74),9));page.addView(add,new LinearLayout.LayoutParams(-1,dp(52)));mg(add,0,12,0,8);add.setOnClickListener(v->materialDialog(-1));
 Button remove=new Button(this);remove.setText("Remove Selected");remove.setAllCaps(false);page.addView(remove,new LinearLayout.LayoutParams(-1,dp(48)));remove.setOnClickListener(v->{ArrayList<Integer> selected=new ArrayList<>();for(CheckBox cb:checks)if(cb.isChecked())selected.add((Integer)cb.getTag());if(selected.isEmpty()){Toast.makeText(this,"Select materials to remove",Toast.LENGTH_SHORT).show();return;}new androidx.appcompat.app.AlertDialog.Builder(this).setTitle("Remove "+selected.size()+" material(s)?").setMessage("Selected materials will be deleted from local storage.").setNegativeButton("Cancel",null).setPositiveButton("Remove",(d,w)->{for(int j=selected.size()-1;j>=0;j--){int idx=selected.get(j);materialNames.remove(idx);materialCats.remove(idx);materialK.remove(idx);materialTensile.remove(idx);}sharedMat=Math.max(0,Math.min(sharedMat,materialNames.size()-1));persistMaterials();showMaterials();}).show();});}
 }
 void materialDialog(int index){boolean editing=index>=0;LinearLayout form=new LinearLayout(this);form.setOrientation(LinearLayout.VERTICAL);form.setPadding(dp(18),dp(8),dp(18),0);EditText name=field(form,"Material Name",editing?materialNames.get(index):"");name.setInputType(InputType.TYPE_CLASS_TEXT);Spinner category=spinner(form,"Category",new String[]{"steel","stainless","aluminum","other"});if(editing){String cat=materialCats.get(index);for(int j=0;j<4;j++)if(category.getItemAtPosition(j).toString().equals(cat))category.setSelection(j);}EditText kval=field(form,"K-Factor",editing?String.valueOf(materialK.get(index)):"0.44");EditText strength=field(form,"Tensile Strength (PSI)",editing?String.format(Locale.US,"%.0f",materialTensile.get(index)):"");new androidx.appcompat.app.AlertDialog.Builder(this).setTitle(editing?"Edit Material":"Add Material").setView(form).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{try{String n=name.getText().toString().trim();double kv=val(kval),ts=val(strength);if(n.isEmpty()||!(kv>0&&kv<1)||!(ts>0))throw new IllegalArgumentException();if(editing){materialNames.set(index,n);materialCats.set(index,category.getSelectedItem().toString());materialK.set(index,kv);materialTensile.set(index,ts);}else{materialNames.add(n);materialCats.add(category.getSelectedItem().toString());materialK.add(kv);materialTensile.add(ts);}persistMaterials();showMaterials();}catch(Exception ex){Toast.makeText(this,"Invalid material values; nothing saved",Toast.LENGTH_LONG).show();}}).show();}

 void showFaq(){shell(3);String[][] x={{"K-Factor","Neutral-axis location through material thickness."},{"Bend Allowance","Arc length of the neutral axis through the bend."},{"Bend Deduction","Amount subtracted from outside flange dimensions to obtain developed flat length."},{"V-Die Opening","Width of the lower die opening used for air bending."},{"Tonnage","Estimated forming force; verify machine and tooling capacity."}};for(String[] q:x){LinearLayout c=card(q[0]);TextView b=t(q[1],14,MUT);c.addView(b);}}
}